from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(850, 400, 241, 313)
        MainWindow.setFixedSize(241, 313)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/clock.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 241, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(10, 40, 101, 31))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 15)
        self.spinBox.setObjectName("spinBox")
        self.apply_button = QtWidgets.QPushButton(self.groupBox)
        self.apply_button.setGeometry(QtCore.QRect(130, 10, 91, 41))
        self.apply_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/apply.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_button.setIcon(icon1)
        self.apply_button.setIconSize(QtCore.QSize(12, 12))
        self.apply_button.setCheckable(False)
        self.apply_button.setObjectName("apply_button")
        self.reset_button = QtWidgets.QPushButton(self.groupBox)
        self.reset_button.setGeometry(QtCore.QRect(130, 50, 91, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/cancel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_button.setIcon(icon2)
        self.reset_button.setIconSize(QtCore.QSize(12, 12))
        self.reset_button.setObjectName("reset_button")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(99, 0, 41, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 80, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 91, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 119, 241, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 211, 31))
        self.comboBox.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox.setStatusTip("")
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/shutdown.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/reboot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        self.apply_button_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.apply_button_2.setGeometry(QtCore.QRect(10, 70, 211, 31))
        self.apply_button_2.setIcon(icon1)
        self.apply_button_2.setIconSize(QtCore.QSize(12, 12))
        self.apply_button_2.setCheckable(False)
        self.apply_button_2.setObjectName("apply_button_2")
        self.exit_button = QtWidgets.QPushButton(self.groupBox_2)
        self.exit_button.setGeometry(QtCore.QRect(10, 120, 211, 31))
        self.exit_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/exit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon5)
        self.exit_button.setIconSize(QtCore.QSize(12, 12))
        self.exit_button.setCheckable(False)
        self.exit_button.setObjectName("exit_button")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(0, 100, 231, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TimerDown"))
        self.apply_button.setStatusTip(_translate("MainWindow", "Click to apply shutdown..."))
        self.apply_button.setText(_translate("MainWindow", "Apply"))
        self.apply_button.clicked.connect(self.apply)
        self.reset_button.setStatusTip(_translate(
            "MainWindow", "Reset your choice and choose again"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.reset_button.clicked.connect(self.reset)
        self.label.setText(_translate("MainWindow", "minutes."))
        self.label_2.setText(_translate("MainWindow", "Shutdown in:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Quick actions:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Quick shutdown"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Quick reboot"))
        self.apply_button_2.setStatusTip(_translate(
            "MainWindow", "Apply quick action of your choice"))
        self.apply_button_2.setText(_translate("MainWindow", "Apply"))
        self.apply_button_2.clicked.connect(self.drop_menu)
        self.exit_button.setStatusTip(_translate("MainWindow", "Exit from TimerDown app"))
        self.exit_button.setText(_translate("MainWindow", "Exit Application"))
        self.exit_button.clicked.connect(self.exit_app)

    def apply(self):
        value = self.spinBox.value()
        os.system(f"shutdown -h {value}")

    def reset(self):
        os.system("shutdown -c")

    def drop_menu(self):
        item = self.comboBox.currentText()
        if item == "Quick shutdown":
            os.system("shutdown -h now")
        else:
            os.system("reboot")

    def exit_app(self):
        sys.exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
